name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 0.5.0
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/kiwi

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:  
  analyzer: ^0.39.0
  build_config: ^0.4.1+1
  code_builder: ^3.2.1
  dart_style: ^1.3.3
  kiwi: '>=0.1.0 <0.3.0'
  path: ^1.6.4
  source_gen: ^0.9.4

dev_dependencies:
  build_runner: ^1.3.4
  build_test: ^0.10.10
  test: ^1.9.4
